services:
  scheduler:
    build:
      context: ./
      dockerfile: docker/scheduler.Dockerfile
    ports:
      - "8000:8000"

  agent1:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    ports:
      - "8001:8001"

  agent2:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    ports:
      - "8002:8001"

  agent3:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    ports:
      - "8003:8001"