services:
  scheduler:
    build:
      context: ./
      dockerfile: docker/scheduler.Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./jobman:/app/jobman

  agent1:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    volumes:
      - ./jobman:/app/jobman

  agent2:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    volumes:
      - ./jobman:/app/jobman

  agent3:
    build:
      context: ./
      dockerfile: docker/agent.Dockerfile
    volumes:
      - ./jobman:/app/jobman
